[package]
name = "async-datachannel"
version = "0.4.0"
edition = "2018"
authors = ["Oliver Wangler <oliver@wngr.de>"]
description = "Async Wrapper for datachannel"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/wngr/async-datachannel"
homepage = "https://github.com/wngr/async-datachannel"
documentation = "https://docs.rs/async-datachannel"
keywords = ["webrtc", "async", "datachannel"]
categories = ["concurrency"]
readme = "README.md"

[dependencies]
anyhow = "1.0.66"
datachannel = "0.8.0"
futures = "0.3.25"
parking_lot = "0.12.1"
serde = { version = "1.0.148", optional = true, features = ["derive"] }
tokio = { version = "1.22.0", features = ["rt"] }
tracing = "0.1.37"

[dev-dependencies]
async-tungstenite = { version = "0.17.2", features = ["tokio-openssl"] }
futures = "0.3.25"
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
tracing-subscriber = "0.3.16"

[features]
default = ["static", "derive"]
static = ["datachannel/vendored"]
derive = ["serde"]

